apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stage
  namespace: argocd
spec:
  destination:
    namespace: stage
    name: kind
  project: default
  sources:
    # Chart from Chart Repo
    - chart: prometheus-community
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.20.1
      helm:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
        valueFiles:
        - $values/applications/app1.yaml
        - $values/applications/app2.yaml
    # Values from Git
    - repoURL: 'https://github.com/A-LPHARM/Rancher-pipeline-with-terraform'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true