apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sources:
    # Chart from Chart Repo
    - chart: bitnami
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 16.0.7
      helm:
        values: |
          replicaCount: 3
    # Values from Git
    - repoURL: 'https://github.com/A-LPHARM/Rancher-pipeline-with-terraform.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true