apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    # Chart from Chart Repo
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.0.7
    helm:
      chart: nginx
      values: |
        replicaCount: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
