apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mointoring
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
     # Chart from Chart Repo
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.5.0
    helm:
      chart: kube-prometheus-stack
      values: |
        replicaCount: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true